version: 2.1
# Uses the official Cypress Orb
# https://circleci.com/developer/orbs/orb/cypress-io/cypress
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          build: "npm run test"
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in CircleCI → Project Settings → Environment Variables
          requires:
            - cypress/install
          # Records to Cypress Dashboard
          # https://docs.cypress.io/guides/dashboard/projects#Set-up-a-project-to-record
          record: false
          
          store_artifacts: true
          # Runs jobs in parallel
          # https://docs.cypress.io/guides/guides/parallelization
          parallel: true
          parallelism: 2 # Uses 2 parallel instances
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          #start: npm start
          wait-on: 'https://kitchen.applitools.com/' # Waits for above

# VS Code Extension Version: 1.5.0